//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LichHoc
    {
        [Display(Name = "Mã Lịch Học")]
        public int MaLH { get; set; }
        [Display(Name = "Mã Lớp Học Phần")]
        public Nullable<int> MaLHP { get; set; }
        [Display(Name = "Mã Phòng")]
        public Nullable<int> MaPhong { get; set; }
        [Display(Name = "Ngày Học")]
        public Nullable<System.DateTime> NgayHoc { get; set; }
        [Display(Name = "Tiết Bắt Đầu")]
        public Nullable<int> TietBatDau { get; set; }
        [Display(Name = "Tiết Kết Thúc")]
        public Nullable<int> TietKetthuc { get; set; }
        [Display(Name = "Giờ Tan Học")]
        public Nullable<System.TimeSpan> GioTanHoc { get; set; }
    
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
    }
}
