//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHocPhan()
        {
            this.LichHocs = new HashSet<LichHoc>();
        }

        [Display(Name = "Mã Lớp Học Phần")]
        public int MaLHP { get; set; }
        [Display(Name = "Mã Môn Học")]
        public Nullable<int> MaMH { get; set; }
        [Display(Name = "Mã Lớp Danh Nghĩa")]
        public Nullable<int> MaLDN { get; set; }
        [Display(Name = "Mã Sĩ Số")]
        public Nullable<int> SiSo { get; set; }
        [Display(Name = "Mã Giảng Viên")]
        public Nullable<int> MaGV { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHoc> LichHocs { get; set; }
        public virtual LopDanhNghia LopDanhNghia { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
